import type { Schema } from "../src/api/finance";

// Synthetic contract-shaped fixtures shared by unit and production-browser tests.
export const owner = {
  id: "aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa",
  email: "synthetic@example.com",
  display_name: "Synthetic",
  email_verified: true,
  timezone: "UTC",
  default_currency: "INR",
} satisfies Schema<"CurrentUserResponse">;

export const goal = {
  created_at: "2026-09-01T00:00:00Z",
  currency: "INR",
  description: null,
  goal_type: "travel",
  id: "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb",
  name: "Trip fund",
  priority: "high",
  starting_amount: "0.0000",
  status: "active",
  target_amount: "1000.1234",
  target_date: "2027-06-01",
  updated_at: "2026-09-01T00:00:00Z",
} satisfies Schema<"GoalResponse">;

export const forecast = {
  candidate_evidence: {},
  contract_version: "synthetic",
  created_at: "2026-09-01T00:00:00Z",
  currency: "INR",
  data_cutoff_at: "2026-09-01T00:00:00Z",
  evaluation_policy_version: "synthetic",
  feature_policy_version: null,
  forecast_end: "2026-10-01",
  forecast_start: "2026-09-01",
  granularity: "month",
  history_end: "2026-08-31",
  history_start: "2026-01-01",
  horizon: 2,
  id: "cccccccc-cccc-4ccc-cccc-cccccccccccc",
  model_code: "mean",
  model_parameters: {},
  model_version: "2026.1",
  points: [
    {
      expected_value: "500.1234",
      lower_80: "400.1234",
      lower_95: "300.1234",
      period_start: "2026-09-01",
      step: 1,
      upper_80: "600.1234",
      upper_95: "700.1234",
    },
    {
      expected_value: "500.1234",
      lower_80: "400.1234",
      lower_95: "300.1234",
      period_start: "2026-10-01",
      step: 2,
      upper_80: "600.1234",
      upper_95: "700.1234",
    },
  ],
  quality_policy_version: "synthetic",
  selection_metric: "mae",
  selection_policy_version: "synthetic",
  source_last_updated_at: null,
  target: "savings_amount",
  test_bias: "0.0000",
  test_mae: "0.0000",
  test_rmse: "0.0000",
  test_wape: null,
  uncertainty_method: "empirical_residual",
  uncertainty_policy_version: "synthetic",
  uncertainty_reliability: "provisional",
  validation_bias: "0.0000",
  validation_mae: "0.0000",
  validation_rmse: "0.0000",
  validation_wape: null,
} satisfies Schema<"ForecastRunResponse">;

export const progress = {
  calculated_on: "2026-09-01",
  contribution_amount: "0.0000",
  currency: "INR",
  current_amount: "0.0000",
  funding_percentage: "0.000000",
  funding_ratio: "0.000000",
  funding_state: "not_started",
  goal_id: "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb",
  goal_name: "Trip fund",
  goal_type: "travel",
  months_remaining: 0,
  priority: "high",
  remaining_amount: "1000.1234",
  required_monthly_contribution: "100.0123",
  starting_amount: "0.0000",
  target_amount: "1000.1234",
  target_date: "2027-06-01",
} satisfies Schema<"GoalProgressResponse">;

export const plan = {
  allocated_savings: "600.0000",
  allocation_band: "95",
  assumptions: ["plan_does_not_move_money", "no_currency_conversion"],
  at_risk_goal_count: 0,
  available_savings: "1000.0000",
  capacity_policy_version: null,
  contract_version: "synthetic",
  created_at: "2026-09-01T00:00:00Z",
  currency: "INR",
  deadline_met_goal_count: 0,
  decided_at: null,
  deterministic_plan_id:
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  emergency_reserve_amount: "0.0000",
  events: [
    {
      occurred_at: "2026-09-01T00:00:00Z",
      previous_status: null,
      reason_code: null,
      source: "system",
      status: "generated",
      successor_plan_id: null,
    },
  ],
  feasibility_policy_version: "synthetic",
  feasible_goal_count: 0,
  forecast_reliability: "provisional",
  forecast_run_id: "cccccccc-cccc-4ccc-cccc-cccccccccccc",
  fully_funded_goal_count: 0,
  goal_count: 1,
  greedy_policy_version: "synthetic",
  greedy_weighted_funding_score: "0.0000",
  guarded_fallback_weighted_funding_score: "0.0000",
  guardrail_policy_version: "synthetic",
  guardrail_reason_codes: [],
  horizon_end: null,
  horizon_start: null,
  id: "dddddddd-dddd-4ddd-dddd-dddddddddddd",
  local_date: "2026-09-01",
  optimization_policy_version: "synthetic",
  optimized_weighted_funding_score: null,
  optimizer_status: null,
  outcomes: [
    {
      allocated_amount: "600.0000",
      completion_probability: null,
      current_amount: "0.0000",
      deadline_met: false,
      deadline_risk: "moderate",
      evidence_reliability: "provisional",
      expected_completion_period: null,
      expected_shortfall: "0.0000",
      feasibility_reason_codes: [],
      feasibility_state: "indeterminate",
      goal_id: "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb",
      goal_name: "Trip fund",
      goal_type: "travel",
      priority: "high",
      projected_completion_period: null,
      projected_remaining_amount: "0.0000",
      protected_shortfall: "400.1234",
      rank: 1,
      ranking_reason_codes: [],
      starting_remaining_amount: "0.0000",
      target_amount: "1000.1234",
      target_date: "2027-06-01",
    },
  ],
  overall_feasibility: "provisional",
  periods: [
    {
      allocated_amount: "600.0000",
      allocations: [
        {
          amount: "600.0000",
          cumulative_amount: "600.0000",
          goal_id: "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb",
          projected_remaining_amount: "400.1234",
          rank: 1,
        },
      ],
      available_capacity: "600.0000",
      period_start: "2026-10-01",
      unallocated_amount: "0.0000",
    },
  ],
  plan_policy_version: "synthetic",
  planning_cutoff_at: "2026-09-01T00:00:00Z",
  predecessor_plan_id: null,
  ranking_policy_version: "synthetic",
  reason_codes: ["solver_unavailable_fallback"],
  selected_score_delta_from_greedy: "0.0000",
  snapshot_id:
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  snapshot_warnings: ["savings_forecast_provisional"],
  solver_name: null,
  solver_version: null,
  status: "generated",
  strategy: "guarded_greedy_fallback",
  successor_plan_id: null,
  timezone: "UTC",
  unallocated_savings: "400.0000",
  uncertain_goal_count: 0,
  weighted_funding_score: "0.0000",
} satisfies Schema<"GoalPlanRunResponse">;

export const snapshot = {
  budgets: {
    active_budget_count: 0,
    budget_with_overall_limit_count: 0,
    source_last_updated_at: null,
    total_overall_limit: "0.0000",
  },
  contract_version: "synthetic",
  currency: "INR",
  cutoff_at: "2026-09-01T00:00:00Z",
  finances: {
    liability_account_count: 0,
    liability_payment_count: 0,
    liquid_balance: "0.0000",
    monthly_debt_payment: "0.0000",
    outstanding_debt: "0.0000",
    source_last_updated_at: null,
  },
  goals: [
    {
      calculated_on: "2026-09-01",
      contribution_amount: "0.0000",
      currency: "INR",
      current_amount: "0.0000",
      funding_percentage: "0.000000",
      funding_ratio: "0.000000",
      funding_state: "not_started",
      goal_id: "bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb",
      goal_name: "Trip fund",
      goal_type: "travel",
      months_remaining: 0,
      priority: "high",
      remaining_amount: "1000.1234",
      required_monthly_contribution: "100.0123",
      starting_amount: "0.0000",
      target_amount: "1000.1234",
      target_date: "2027-06-01",
    },
  ],
  local_date: "2026-09-01",
  profile: null,
  provenance: {
    contribution_count: 0,
    forecast_run_id: null,
    goal_ids: [],
    source_last_updated_at: null,
  },
  savings_capacity: null,
  snapshot_id: "synthetic",
  timezone: "UTC",
  warnings: ["savings_forecast_provisional"],
} satisfies Schema<"GoalPlanningSnapshotResponse">;

export const context = {
  comparison_period: null,
  completeness: {
    abstained_transaction_count: 0,
    categorized_transaction_count: 1,
    classification_coverage: "1.000000",
    data_confidence: "low",
    eligible_transaction_count: 1,
    exclusions: {
      adjustment_count: 0,
      other_currency_count: 0,
      pending_count: 0,
      transfer_entry_count: 0,
    },
    suggested_transaction_count: 0,
  },
  contract_version: "2026.1",
  currency: "INR",
  freshness: {
    calculated_at: "2026-09-01T00:00:00Z",
    latest_transaction_date: null,
    materialized: false,
    source_last_updated_at: null,
  },
  period: {
    date_from: "2026-09-01",
    date_to: "2026-09-30",
    day_count: 30,
    timezone: "UTC",
  },
} satisfies Schema<"AnalyticsContext">;

export const cash = {
  context: {
    comparison_period: null,
    completeness: {
      abstained_transaction_count: 0,
      categorized_transaction_count: 1,
      classification_coverage: "1.000000",
      data_confidence: "low",
      eligible_transaction_count: 1,
      exclusions: {
        adjustment_count: 0,
        other_currency_count: 0,
        pending_count: 0,
        transfer_entry_count: 0,
      },
      suggested_transaction_count: 0,
    },
    contract_version: "2026.1",
    currency: "INR",
    freshness: {
      calculated_at: "2026-09-01T00:00:00Z",
      latest_transaction_date: null,
      materialized: false,
      source_last_updated_at: null,
    },
    period: {
      date_from: "2026-09-01",
      date_to: "2026-09-30",
      day_count: 30,
      timezone: "UTC",
    },
  },
  granularity: "month",
  metrics: {
    gross_income: {
      value: "0.0000",
    },
    internal_transfer_volume: {
      value: "0.0000",
    },
    net_adjustment: {
      value: "0.0000",
    },
    net_cash_flow: {
      value: "0.0000",
    },
    savings_amount: {
      value: "0.0000",
    },
    savings_rate: {
      value: null,
    },
    total_expense: {
      value: "123.4567",
    },
  },
  previous_period: null,
  series: [],
} satisfies Schema<"CashFlowAnalyticsResponse">;

export const spending = {
  accounts: [
    {
      account_id: "eeeeeeee-eeee-4eee-eeee-eeeeeeeeeeee",
      account_type: "bank",
      amount: {
        value: "123.4567",
      },
      name: "Synthetic bank",
      share: {
        value: "1.000000",
      },
      transaction_count: 1,
    },
  ],
  categories: [],
  context: {
    comparison_period: null,
    completeness: {
      abstained_transaction_count: 0,
      categorized_transaction_count: 1,
      classification_coverage: "1.000000",
      data_confidence: "low",
      eligible_transaction_count: 1,
      exclusions: {
        adjustment_count: 0,
        other_currency_count: 0,
        pending_count: 0,
        transfer_entry_count: 0,
      },
      suggested_transaction_count: 0,
    },
    contract_version: "2026.1",
    currency: "INR",
    freshness: {
      calculated_at: "2026-09-01T00:00:00Z",
      latest_transaction_date: null,
      materialized: false,
      source_last_updated_at: null,
    },
    period: {
      date_from: "2026-09-01",
      date_to: "2026-09-30",
      day_count: 30,
      timezone: "UTC",
    },
  },
  merchants: [],
  previous_period_total_expense: null,
  total_expense: {
    value: "0.0000",
  },
} satisfies Schema<"SpendingAnalyticsResponse">;
