"""Versioned forecasting contracts and source-series foundation."""

from falcon_api.forecasting.baselines import (
    DriftBaseline,
    HistoricalMeanBaseline,
    HistoricalMedianBaseline,
    LastValueBaseline,
    MovingAverageBaseline,
    SeasonalNaiveBaseline,
    baseline_candidates,
)
from falcon_api.forecasting.evaluation import (
    FORECAST_EVALUATION_POLICY_VERSION,
    CandidateEvaluation,
    ChronologicalEvaluationPlan,
    EvaluationFold,
    FoldEvaluation,
    ForecastCandidate,
    ForecastErrorMetrics,
    RollingOriginConfig,
    build_chronological_evaluation_plan,
    calculate_forecast_error_metrics,
    evaluate_candidate,
)
from falcon_api.forecasting.periods import ForecastHistoryWindow
from falcon_api.forecasting.quality import (
    FORECAST_QUALITY_POLICY_VERSION,
    ForecastEligibility,
    ForecastQualityAssessment,
    ForecastQualityReason,
    assess_forecast_quality,
)
from falcon_api.forecasting.repository import ForecastingRepository
from falcon_api.forecasting.semantics import (
    FORECASTING_CONTRACT_VERSION,
    FORECAST_TARGET_DEFINITIONS,
    MAX_DAILY_FORECAST_HORIZON,
    MAX_FORECAST_HISTORY_DAYS,
    MAX_MONTHLY_FORECAST_HORIZON,
    MIN_NORMAL_HISTORY_MONTHS,
    ForecastErrorCode,
    ForecastGranularity,
    ForecastTarget,
    ForecastTargetDefinition,
    forecast_target_definition,
    normalize_forecast_currency,
    validate_forecast_horizon,
)
from falcon_api.forecasting.series import build_forecast_series
from falcon_api.forecasting.types import (
    ForecastSeries,
    ForecastSeriesPoint,
    ForecastSourceBucket,
)

__all__ = (
    "FORECASTING_CONTRACT_VERSION",
    "FORECAST_EVALUATION_POLICY_VERSION",
    "FORECAST_QUALITY_POLICY_VERSION",
    "FORECAST_TARGET_DEFINITIONS",
    "MAX_DAILY_FORECAST_HORIZON",
    "MAX_FORECAST_HISTORY_DAYS",
    "MAX_MONTHLY_FORECAST_HORIZON",
    "MIN_NORMAL_HISTORY_MONTHS",
    "CandidateEvaluation",
    "ChronologicalEvaluationPlan",
    "DriftBaseline",
    "EvaluationFold",
    "FoldEvaluation",
    "ForecastCandidate",
    "ForecastEligibility",
    "ForecastErrorCode",
    "ForecastErrorMetrics",
    "ForecastGranularity",
    "ForecastHistoryWindow",
    "ForecastQualityAssessment",
    "ForecastQualityReason",
    "ForecastSeries",
    "ForecastSeriesPoint",
    "ForecastSourceBucket",
    "ForecastTarget",
    "ForecastTargetDefinition",
    "ForecastingRepository",
    "HistoricalMeanBaseline",
    "HistoricalMedianBaseline",
    "LastValueBaseline",
    "MovingAverageBaseline",
    "RollingOriginConfig",
    "SeasonalNaiveBaseline",
    "assess_forecast_quality",
    "baseline_candidates",
    "build_forecast_series",
    "build_chronological_evaluation_plan",
    "calculate_forecast_error_metrics",
    "evaluate_candidate",
    "forecast_target_definition",
    "normalize_forecast_currency",
    "validate_forecast_horizon",
)
