"""Stable contracts for transaction classification."""

from falcon_api.classification.artifacts import (
    MODEL_ARTIFACT_MANIFEST_VERSION,
    ClassifierArtifactCompatibilityError,
    ClassifierArtifactError,
    ClassifierArtifactIntegrityError,
    ClassifierArtifactUnavailableError,
    LazyClassifierProvider,
    LibraryVersion,
    ModelArtifactManifest,
    ModelArtifactRegistry,
)
from falcon_api.classification.dataset import (
    CLASSIFICATION_DATASET_VERSION,
    ClassificationDataset,
    ClassificationDatasetManifest,
    DatasetLabelCount,
    DatasetRecord,
    DatasetSourceKind,
    LabeledFeatureSample,
    build_classification_dataset,
    load_classification_dataset,
)
from falcon_api.classification.features import (
    CLASSIFICATION_FEATURE_SCHEMA_VERSION,
    AmountBand,
    ClassificationFeatures,
    PaymentChannel,
    TransactionFeatureInput,
    amount_band,
    build_classification_features,
    classification_model_text,
    detect_payment_channel,
    feature_record,
    normalize_merchant,
)
from falcon_api.classification.hybrid import (
    HybridClassificationOutcome,
    HybridClassificationService,
    MerchantMemoryMatch,
)
from falcon_api.classification.explanations import explanation_message
from falcon_api.classification.inference import (
    ClassifierMetadata,
    ConfidencePolicy,
    ModelCandidate,
    ModelPrediction,
    SklearnTransactionClassifier,
    TransactionClassifier,
)
from falcon_api.classification.merchant_knowledge import (
    DEFAULT_MERCHANT_DEFINITIONS,
    DEFAULT_MERCHANT_KNOWLEDGE_BASE,
    MERCHANT_KNOWLEDGE_VERSION,
    MerchantDefinition,
    MerchantKnowledgeBase,
)
from falcon_api.classification.monitoring import (
    ClassificationMonitor,
    ClassificationOperation,
)
from falcon_api.classification.rules import (
    CLASSIFICATION_RULESET_VERSION,
    DEFAULT_KEYWORD_RULES,
    ClassificationRulesEngine,
    KeywordRule,
    RuleEvaluation,
    RuleMatch,
    RuleMatchKind,
)
from falcon_api.classification.taxonomy import (
    CLASSIFICATION_TAXONOMY_VERSION,
    CATEGORY_DEFINITIONS,
    CategoryDefinition,
    ClassificationCategoryCode,
    ClassificationSubcategoryCode,
    SubcategoryDefinition,
    category_definition,
    subcategory_definition,
    validate_classification_target,
)
from falcon_api.classification.types import (
    ClassificationDecision,
    ClassificationReasonCode,
    ClassificationSource,
)


__all__ = [
    "CLASSIFICATION_DATASET_VERSION",
    "CLASSIFICATION_FEATURE_SCHEMA_VERSION",
    "CLASSIFICATION_RULESET_VERSION",
    "CATEGORY_DEFINITIONS",
    "CLASSIFICATION_TAXONOMY_VERSION",
    "MODEL_ARTIFACT_MANIFEST_VERSION",
    "AmountBand",
    "CategoryDefinition",
    "ClassificationFeatures",
    "ClassificationMonitor",
    "ClassificationOperation",
    "ClassificationDecision",
    "ClassificationReasonCode",
    "ClassificationRulesEngine",
    "ClassificationSource",
    "ClassificationCategoryCode",
    "ClassificationDataset",
    "ClassificationDatasetManifest",
    "ClassificationSubcategoryCode",
    "ClassifierArtifactCompatibilityError",
    "ClassifierArtifactError",
    "ClassifierArtifactIntegrityError",
    "ClassifierArtifactUnavailableError",
    "ClassifierMetadata",
    "ConfidencePolicy",
    "DatasetLabelCount",
    "DatasetRecord",
    "DatasetSourceKind",
    "PaymentChannel",
    "DEFAULT_KEYWORD_RULES",
    "DEFAULT_MERCHANT_DEFINITIONS",
    "DEFAULT_MERCHANT_KNOWLEDGE_BASE",
    "KeywordRule",
    "HybridClassificationOutcome",
    "HybridClassificationService",
    "LabeledFeatureSample",
    "MERCHANT_KNOWLEDGE_VERSION",
    "MerchantDefinition",
    "MerchantKnowledgeBase",
    "MerchantMemoryMatch",
    "LazyClassifierProvider",
    "LibraryVersion",
    "ModelArtifactManifest",
    "ModelArtifactRegistry",
    "ModelCandidate",
    "ModelPrediction",
    "RuleEvaluation",
    "RuleMatch",
    "RuleMatchKind",
    "SubcategoryDefinition",
    "SklearnTransactionClassifier",
    "TransactionClassifier",
    "TransactionFeatureInput",
    "amount_band",
    "build_classification_dataset",
    "build_classification_features",
    "classification_model_text",
    "category_definition",
    "detect_payment_channel",
    "feature_record",
    "explanation_message",
    "load_classification_dataset",
    "normalize_merchant",
    "subcategory_definition",
    "validate_classification_target",
]
