"""create initial domain schema

Revision ID: 771fa3a74464
Revises: 25efb498276a
Create Date: 2026-08-15 12:12:30.152239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771fa3a74464'
down_revision: Union[str, Sequence[str], None] = '25efb498276a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("default_currency ~ '^[A-Z]{3}$'", name=op.f('ck_users_default_currency_iso')),
    sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f('ck_users_status_allowed')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_normalized')),
    sa.CheckConstraint('length(trim(email)) >= 3', name=op.f('ck_users_email_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('account_type', sa.String(length=24), nullable=False),
    sa.Column('institution_name', sa.String(length=160), nullable=True),
    sa.Column('masked_reference', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('opening_balance_date', sa.Date(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("account_type IN ('bank', 'cash', 'wallet', 'credit_card', 'investment', 'loan')", name=op.f('ck_accounts_account_type_allowed')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_accounts_currency_iso')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_accounts_name_not_blank')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_accounts_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('user_id', 'id', name='uq_accounts_user_id_id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_accounts_user_name')
    )
    op.create_index('ix_accounts_user_active', 'accounts', ['user_id'], unique=False, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index('ix_accounts_user_type', 'accounts', ['user_id', 'account_type'], unique=False)
    op.create_table('budgets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('overall_limit', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_budgets_currency_iso')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_budgets_name_not_blank')),
    sa.CheckConstraint('overall_limit IS NULL OR overall_limit > 0', name=op.f('ck_budgets_overall_limit_positive')),
    sa.CheckConstraint('period_end_date >= period_start_date', name=op.f('ck_budgets_period_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_budgets_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('user_id', 'id', name='uq_budgets_user_id_id'),
    sa.UniqueConstraint('user_id', 'name', 'period_start_date', 'period_end_date', name='uq_budgets_user_name_period')
    )
    op.create_index('ix_budgets_user_active_period', 'budgets', ['user_id', 'period_start_date', 'period_end_date'], unique=False, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_table('categories',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('income', 'expense', 'transfer')", name=op.f('ck_categories_kind_allowed')),
    sa.CheckConstraint('(is_system AND user_id IS NULL) OR (NOT is_system AND user_id IS NOT NULL)', name=op.f('ck_categories_system_owner_consistent')),
    sa.CheckConstraint('display_order >= 0', name=op.f('ck_categories_display_order_non_negative')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_categories_name_not_blank')),
    sa.CheckConstraint('length(trim(normalized_name)) > 0', name=op.f('ck_categories_normalized_name_not_blank')),
    sa.CheckConstraint('normalized_name = lower(normalized_name)', name=op.f('ck_categories_normalized_name_lowercase')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='fk_categories_parent_id_categories', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_categories_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('ix_categories_user_active', 'categories', ['user_id'], unique=False, postgresql_where=sa.text('NOT is_system AND archived_at IS NULL'))
    op.create_index('uq_categories_system_name', 'categories', ['normalized_name'], unique=True, postgresql_where=sa.text('is_system'))
    op.create_index('uq_categories_user_name', 'categories', ['user_id', 'normalized_name'], unique=True, postgresql_where=sa.text('NOT is_system'))
    op.create_table('financial_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('income_pattern', sa.String(length=24), nullable=True),
    sa.Column('income_stability', sa.String(length=16), nullable=True),
    sa.Column('has_household_responsibilities', sa.Boolean(), nullable=False),
    sa.Column('dependant_count', sa.Integer(), nullable=False),
    sa.Column('emergency_fund_target_months', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('completion_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("completion_status IN ('draft', 'complete')", name=op.f('ck_financial_profiles_completion_status_allowed')),
    sa.CheckConstraint("income_pattern IS NULL OR income_pattern IN ('salaried', 'self_employed', 'irregular', 'mixed')", name=op.f('ck_financial_profiles_income_pattern_allowed')),
    sa.CheckConstraint("income_stability IS NULL OR income_stability IN ('stable', 'variable', 'unstable')", name=op.f('ck_financial_profiles_income_stability_allowed')),
    sa.CheckConstraint('dependant_count >= 0', name=op.f('ck_financial_profiles_dependant_count_non_negative')),
    sa.CheckConstraint('emergency_fund_target_months IS NULL OR emergency_fund_target_months >= 0', name=op.f('ck_financial_profiles_emergency_fund_target_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_financial_profiles_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_financial_profiles_user_id'))
    )
    op.create_table('goals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('goal_type', sa.String(length=24), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('starting_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_goals_currency_iso')),
    sa.CheckConstraint("goal_type IN ('travel', 'marriage', 'education', 'emergency_fund', 'major_purchase', 'other')", name=op.f('ck_goals_goal_type_allowed')),
    sa.CheckConstraint("priority IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_goals_priority_allowed')),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled')", name=op.f('ck_goals_status_allowed')),
    sa.CheckConstraint('length(trim(name)) > 0', name=op.f('ck_goals_name_not_blank')),
    sa.CheckConstraint('starting_amount <= target_amount', name=op.f('ck_goals_starting_not_above_target')),
    sa.CheckConstraint('starting_amount >= 0', name=op.f('ck_goals_starting_amount_non_negative')),
    sa.CheckConstraint('target_amount > 0', name=op.f('ck_goals_target_amount_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_goals_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals')),
    sa.UniqueConstraint('user_id', 'id', name='uq_goals_user_id_id')
    )
    op.create_index('ix_goals_user_priority_deadline', 'goals', ['user_id', 'priority', 'target_date'], unique=False)
    op.create_index('ix_goals_user_status_deadline', 'goals', ['user_id', 'status', 'target_date'], unique=False)
    op.create_table('import_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('failure_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source_type IN ('csv', 'excel', 'bank_statement', 'credit_card_statement', 'paytm', 'phonepe', 'google_pay')", name=op.f('ck_import_jobs_source_type_allowed')),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'partial', 'failed')", name=op.f('ck_import_jobs_status_allowed')),
    sa.CheckConstraint('accepted_count >= 0', name=op.f('ck_import_jobs_accepted_count_non_negative')),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_import_jobs_completion_not_before_start')),
    sa.CheckConstraint('rejected_count >= 0', name=op.f('ck_import_jobs_rejected_count_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_import_jobs_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs')),
    sa.UniqueConstraint('user_id', 'file_fingerprint', name='uq_import_jobs_user_fingerprint'),
    sa.UniqueConstraint('user_id', 'id', name='uq_import_jobs_user_id_id')
    )
    op.create_index('ix_import_jobs_user_status_created', 'import_jobs', ['user_id', 'status', 'created_at'], unique=False)
    op.create_table('transfer_groups',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_transfer_groups_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_groups')),
    sa.UniqueConstraint('user_id', 'id', name='uq_transfer_groups_user_id_id')
    )
    op.create_index('ix_transfer_groups_user_created', 'transfer_groups', ['user_id', 'created_at'], unique=False)
    op.create_table('budget_limits',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('budget_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('limit_amount > 0', name=op.f('ck_budget_limits_limit_amount_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_budget_limits_category_id_categories', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'budget_id'], ['budgets.user_id', 'budgets.id'], name='fk_budget_limits_owner_budget', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_budget_limits_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_limits')),
    sa.UniqueConstraint('budget_id', 'category_id', name='uq_budget_limits_budget_category')
    )
    op.create_index('ix_budget_limits_category', 'budget_limits', ['category_id'], unique=False)
    op.create_table('liability_details',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('liability_subtype', sa.String(length=24), nullable=False),
    sa.Column('principal_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('annual_interest_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('minimum_payment', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("liability_subtype IN ('loan', 'credit_card')", name=op.f('ck_liability_details_liability_subtype_allowed')),
    sa.CheckConstraint('annual_interest_rate IS NULL OR (annual_interest_rate >= 0 AND annual_interest_rate <= 1)', name=op.f('ck_liability_details_annual_interest_rate_range')),
    sa.CheckConstraint('maturity_date IS NULL OR start_date IS NULL OR maturity_date >= start_date', name=op.f('ck_liability_details_maturity_not_before_start')),
    sa.CheckConstraint('minimum_payment IS NULL OR minimum_payment >= 0', name=op.f('ck_liability_details_minimum_payment_non_negative')),
    sa.CheckConstraint('outstanding_amount IS NULL OR outstanding_amount >= 0', name=op.f('ck_liability_details_outstanding_non_negative')),
    sa.CheckConstraint('payment_due_day IS NULL OR payment_due_day BETWEEN 1 AND 31', name=op.f('ck_liability_details_payment_due_day_range')),
    sa.CheckConstraint('principal_amount IS NULL OR principal_amount >= 0', name=op.f('ck_liability_details_principal_non_negative')),
    sa.ForeignKeyConstraint(['user_id', 'account_id'], ['accounts.user_id', 'accounts.id'], name='fk_liability_details_owner_account', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liability_details')),
    sa.UniqueConstraint('account_id', name='uq_liability_details_account_id')
    )
    op.create_table('transactions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('import_job_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_group_id', sa.Uuid(), nullable=True),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('external_source_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_user_modified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(source_type = 'import' AND import_job_id IS NOT NULL) OR (source_type <> 'import' AND import_job_id IS NULL)", name=op.f('ck_transactions_import_job_consistent')),
    sa.CheckConstraint("(transaction_type = 'transfer' AND transfer_group_id IS NOT NULL) OR (transaction_type <> 'transfer' AND transfer_group_id IS NULL)", name=op.f('ck_transactions_transfer_group_consistent')),
    sa.CheckConstraint("source_type IN ('manual', 'import', 'transfer', 'adjustment')", name=op.f('ck_transactions_source_type_allowed')),
    sa.CheckConstraint("status IN ('pending', 'posted')", name=op.f('ck_transactions_status_allowed')),
    sa.CheckConstraint("transaction_type IN ('income', 'expense', 'transfer', 'adjustment')", name=op.f('ck_transactions_transaction_type_allowed')),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_transactions_amount_non_zero')),
    sa.CheckConstraint('length(trim(description)) > 0', name=op.f('ck_transactions_description_not_blank')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_transactions_category_id_categories', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'account_id'], ['accounts.user_id', 'accounts.id'], name='fk_transactions_owner_account', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'import_job_id'], ['import_jobs.user_id', 'import_jobs.id'], name='fk_transactions_owner_import_job', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id', 'transfer_group_id'], ['transfer_groups.user_id', 'transfer_groups.id'], name='fk_transactions_owner_transfer_group', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_transactions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('user_id', 'id', name='uq_transactions_user_id_id')
    )
    op.create_index('ix_transactions_account_date', 'transactions', ['account_id', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_category_date', 'transactions', ['category_id', 'transaction_date'], unique=False)
    op.create_index('ix_transactions_import_job', 'transactions', ['import_job_id'], unique=False, postgresql_where=sa.text('import_job_id IS NOT NULL'))
    op.create_index('ix_transactions_transfer_group', 'transactions', ['transfer_group_id'], unique=False, postgresql_where=sa.text('transfer_group_id IS NOT NULL'))
    op.create_index('ix_transactions_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index('uq_transactions_user_account_source_hash', 'transactions', ['user_id', 'account_id', 'external_source_hash'], unique=True, postgresql_where=sa.text('external_source_hash IS NOT NULL'))
    op.create_table('goal_contributions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('contribution_date', sa.Date(), nullable=False),
    sa.Column('source_type', sa.String(length=24), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(source_type = 'transaction' AND transaction_id IS NOT NULL) OR (source_type <> 'transaction' AND transaction_id IS NULL)", name=op.f('ck_goal_contributions_transaction_source_consistent')),
    sa.CheckConstraint("source_type IN ('manual', 'transaction', 'opening_balance')", name=op.f('ck_goal_contributions_source_type_allowed')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_goal_contributions_amount_positive')),
    sa.ForeignKeyConstraint(['user_id', 'goal_id'], ['goals.user_id', 'goals.id'], name='fk_goal_contributions_owner_goal', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'transaction_id'], ['transactions.user_id', 'transactions.id'], name='fk_goal_contributions_owner_transaction', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_goal_contributions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goal_contributions'))
    )
    op.create_index('ix_goal_contributions_goal_date', 'goal_contributions', ['goal_id', 'contribution_date'], unique=False)
    op.create_index('ix_goal_contributions_transaction', 'goal_contributions', ['transaction_id'], unique=False, postgresql_where=sa.text('transaction_id IS NOT NULL'))
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE FUNCTION falcon_validate_category_scope()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        DECLARE
            parent_user_id uuid;
            parent_is_system boolean;
            parent_kind varchar;
        BEGIN
            IF NEW.parent_id IS NOT NULL THEN
                IF NEW.parent_id = NEW.id THEN
                    RAISE EXCEPTION
                        'A category cannot be its own parent.'
                        USING ERRCODE = '23514';
                END IF;

                SELECT user_id, is_system, kind
                INTO parent_user_id, parent_is_system, parent_kind
                FROM categories
                WHERE id = NEW.parent_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION
                        'The parent category does not exist.'
                        USING ERRCODE = '23503';
                END IF;

                IF parent_kind <> NEW.kind THEN
                    RAISE EXCEPTION
                        'Parent and child category kinds must match.'
                        USING ERRCODE = '23514';
                END IF;

                IF NEW.is_system AND NOT parent_is_system THEN
                    RAISE EXCEPTION
                        'A system category requires a system parent.'
                        USING ERRCODE = '23514';
                END IF;

                IF (
                    NOT NEW.is_system
                    AND NOT parent_is_system
                    AND parent_user_id IS DISTINCT FROM NEW.user_id
                ) THEN
                    RAISE EXCEPTION
                        'Custom category parent ownership must match.'
                        USING ERRCODE = '23514';
                END IF;
            END IF;

            IF TG_OP = 'UPDATE' AND (
                OLD.user_id IS DISTINCT FROM NEW.user_id
                OR OLD.is_system IS DISTINCT FROM NEW.is_system
                OR OLD.kind IS DISTINCT FROM NEW.kind
            ) THEN
                IF EXISTS (
                    SELECT 1
                    FROM categories AS child
                    WHERE child.parent_id = NEW.id
                    AND (
                        child.kind <> NEW.kind
                        OR (
                            child.is_system
                            AND NOT NEW.is_system
                        )
                        OR (
                            NOT child.is_system
                            AND NOT NEW.is_system
                            AND child.user_id IS DISTINCT FROM NEW.user_id
                        )
                    )
                ) THEN
                    RAISE EXCEPTION
                        'Category scope change would invalidate a child.'
                        USING ERRCODE = '23514';
                END IF;
            END IF;

            RETURN NEW;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_categories_validate_scope
        BEFORE INSERT OR UPDATE OF
            user_id,
            is_system,
            kind,
            parent_id
        ON categories
        FOR EACH ROW
        EXECUTE FUNCTION falcon_validate_category_scope();
        """
    )
    op.execute(
        """
        CREATE FUNCTION falcon_assert_transfer_group_valid(
            checked_group_id uuid
        )
        RETURNS void
        LANGUAGE plpgsql
        AS $$
        DECLARE
            entry_count integer;
            account_count integer;
            currency_count integer;
            types_valid boolean;
            sources_valid boolean;
            net_amount numeric;
        BEGIN
            IF checked_group_id IS NULL THEN
                RETURN;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM transfer_groups
                WHERE id = checked_group_id
            ) THEN
                RETURN;
            END IF;

            SELECT
                count(*)::integer,
                count(DISTINCT transaction_row.account_id)::integer,
                count(DISTINCT account_row.currency)::integer,
                coalesce(
                    bool_and(
                        transaction_row.transaction_type = 'transfer'
                    ),
                    false
                ),
                coalesce(
                    bool_and(
                        transaction_row.source_type = 'transfer'
                    ),
                    false
                ),
                coalesce(sum(transaction_row.amount), 0)
            INTO
                entry_count,
                account_count,
                currency_count,
                types_valid,
                sources_valid,
                net_amount
            FROM transactions AS transaction_row
            JOIN accounts AS account_row
                ON account_row.id = transaction_row.account_id
                AND account_row.user_id = transaction_row.user_id
            WHERE transaction_row.transfer_group_id = checked_group_id;

            IF (
                entry_count <> 2
                OR account_count <> 2
                OR currency_count <> 1
                OR NOT types_valid
                OR NOT sources_valid
                OR net_amount <> 0
            ) THEN
                RAISE EXCEPTION
                    'Transfer group % must contain two opposite, '
                    'same-currency entries on distinct accounts.',
                    checked_group_id
                    USING ERRCODE = '23514';
            END IF;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE FUNCTION falcon_enforce_transfer_integrity()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_TABLE_NAME = 'transfer_groups' THEN
                PERFORM falcon_assert_transfer_group_valid(NEW.id);
                RETURN NULL;
            END IF;

            IF TG_OP <> 'INSERT' AND OLD.transfer_group_id IS NOT NULL THEN
                PERFORM falcon_assert_transfer_group_valid(
                    OLD.transfer_group_id
                );
            END IF;

            IF (
                TG_OP <> 'DELETE'
                AND NEW.transfer_group_id IS NOT NULL
                AND (
                    TG_OP = 'INSERT'
                    OR NEW.transfer_group_id
                        IS DISTINCT FROM OLD.transfer_group_id
                )
            ) THEN
                PERFORM falcon_assert_transfer_group_valid(
                    NEW.transfer_group_id
                );
            END IF;

            RETURN NULL;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER trg_transfer_groups_pair_integrity
        AFTER INSERT OR UPDATE
        ON transfer_groups
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION falcon_enforce_transfer_integrity();
        """
    )
    op.execute(
        """
        CREATE CONSTRAINT TRIGGER trg_transactions_transfer_integrity
        AFTER INSERT OR UPDATE OR DELETE
        ON transactions
        DEFERRABLE INITIALLY DEFERRED
        FOR EACH ROW
        EXECUTE FUNCTION falcon_enforce_transfer_integrity();
        """
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_goal_contributions_transaction', table_name='goal_contributions', postgresql_where=sa.text('transaction_id IS NOT NULL'))
    op.execute(
        """
        DROP TRIGGER IF EXISTS
            trg_transactions_transfer_integrity
        ON transactions;
        """
    )
    op.execute(
        """
        DROP TRIGGER IF EXISTS
            trg_transfer_groups_pair_integrity
        ON transfer_groups;
        """
    )
    op.execute(
        """
        DROP FUNCTION IF EXISTS falcon_enforce_transfer_integrity();
        """
    )
    op.execute(
        """
        DROP FUNCTION IF EXISTS
            falcon_assert_transfer_group_valid(uuid);
        """
    )
    op.execute(
        """
        DROP TRIGGER IF EXISTS
            trg_categories_validate_scope
        ON categories;
        """
    )
    op.execute(
        """
        DROP FUNCTION IF EXISTS falcon_validate_category_scope();
        """
    )
    op.drop_index('ix_goal_contributions_goal_date', table_name='goal_contributions')
    op.drop_table('goal_contributions')
    op.drop_index('uq_transactions_user_account_source_hash', table_name='transactions', postgresql_where=sa.text('external_source_hash IS NOT NULL'))
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.drop_index('ix_transactions_transfer_group', table_name='transactions', postgresql_where=sa.text('transfer_group_id IS NOT NULL'))
    op.drop_index('ix_transactions_import_job', table_name='transactions', postgresql_where=sa.text('import_job_id IS NOT NULL'))
    op.drop_index('ix_transactions_category_date', table_name='transactions')
    op.drop_index('ix_transactions_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('liability_details')
    op.drop_index('ix_budget_limits_category', table_name='budget_limits')
    op.drop_table('budget_limits')
    op.drop_index('ix_transfer_groups_user_created', table_name='transfer_groups')
    op.drop_table('transfer_groups')
    op.drop_index('ix_import_jobs_user_status_created', table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index('ix_goals_user_status_deadline', table_name='goals')
    op.drop_index('ix_goals_user_priority_deadline', table_name='goals')
    op.drop_table('goals')
    op.drop_table('financial_profiles')
    op.drop_index('uq_categories_user_name', table_name='categories', postgresql_where=sa.text('NOT is_system'))
    op.drop_index('uq_categories_system_name', table_name='categories', postgresql_where=sa.text('is_system'))
    op.drop_index('ix_categories_user_active', table_name='categories', postgresql_where=sa.text('NOT is_system AND archived_at IS NULL'))
    op.drop_table('categories')
    op.drop_index('ix_budgets_user_active_period', table_name='budgets', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_table('budgets')
    op.drop_index('ix_accounts_user_type', table_name='accounts')
    op.drop_index('ix_accounts_user_active', table_name='accounts', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
