"""add authentication persistence foundation

Revision ID: 7fff19ce50be
Revises: a1b1833784e5
Create Date: 2026-08-15 16:29:12.890407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fff19ce50be'
down_revision: Union[str, Sequence[str], None] = 'a1b1833784e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authentication_challenges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("purpose IN ('email_verification', 'password_reset')", name=op.f('ck_authentication_challenges_purpose_allowed')),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_authentication_challenges_token_hash_sha256_hex')),
    sa.CheckConstraint('consumed_at IS NULL OR consumed_at >= created_at', name=op.f('ck_authentication_challenges_consumption_not_before_creation')),
    sa.CheckConstraint('consumed_at IS NULL OR invalidated_at IS NULL', name=op.f('ck_authentication_challenges_terminal_state_exclusive')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_authentication_challenges_expiry_after_creation')),
    sa.CheckConstraint('invalidated_at IS NULL OR invalidated_at >= created_at', name=op.f('ck_authentication_challenges_invalidation_not_before_creation')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_authentication_challenges_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authentication_challenges')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_authentication_challenges_token_hash'))
    )
    op.create_index('ix_authentication_challenges_expiry', 'authentication_challenges', ['expires_at'], unique=False)
    op.create_index('uq_authentication_challenges_user_purpose_active', 'authentication_challenges', ['user_id', 'purpose'], unique=True, postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(revoked_at IS NULL AND revocation_reason IS NULL) OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)', name=op.f('ck_refresh_sessions_revocation_state_consistent')),
    sa.CheckConstraint('expires_at > created_at', name=op.f('ck_refresh_sessions_expiry_after_creation')),
    sa.CheckConstraint('last_used_at IS NULL OR last_used_at <= expires_at', name=op.f('ck_refresh_sessions_last_used_not_after_expiry')),
    sa.CheckConstraint('last_used_at IS NULL OR last_used_at >= created_at', name=op.f('ck_refresh_sessions_last_used_not_before_creation')),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name=op.f('ck_refresh_sessions_revocation_not_before_creation')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_refresh_sessions_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions'))
    )
    op.create_index('ix_refresh_sessions_expiry', 'refresh_sessions', ['expires_at'], unique=False)
    op.create_index('ix_refresh_sessions_family', 'refresh_sessions', ['family_id'], unique=False)
    op.create_index('ix_refresh_sessions_user_active', 'refresh_sessions', ['user_id', 'expires_at'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('user_credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("password_hash LIKE '$argon2id$%%'", name=op.f('ck_user_credentials_password_hash_argon2id')),
    sa.CheckConstraint('length(password_hash) BETWEEN 32 AND 512', name=op.f('ck_user_credentials_password_hash_length')),
    sa.CheckConstraint('password_changed_at >= created_at', name=op.f('ck_user_credentials_password_changed_not_before_creation')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_credentials_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_credentials')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_credentials_user_id'))
    )
    op.create_table('authentication_delivery_outbox',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('challenge_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('encryption_key_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(status = 'sent' AND processed_at IS NOT NULL) OR (status <> 'sent' AND processed_at IS NULL)", name=op.f('ck_authentication_delivery_outbox_processing_state_consistent')),
    sa.CheckConstraint("status IN ('pending', 'processing', 'sent', 'failed')", name=op.f('ck_authentication_delivery_outbox_status_allowed')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_authentication_delivery_outbox_attempt_count_non_negative')),
    sa.CheckConstraint('processed_at IS NULL OR processed_at >= created_at', name=op.f('ck_authentication_delivery_outbox_processed_not_before_creation')),
    sa.ForeignKeyConstraint(['challenge_id'], ['authentication_challenges.id'], name='fk_auth_delivery_outbox_challenge', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_authentication_delivery_outbox_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authentication_delivery_outbox')),
    sa.UniqueConstraint('challenge_id', name=op.f('uq_authentication_delivery_outbox_challenge_id'))
    )
    op.create_index('ix_authentication_delivery_outbox_pending', 'authentication_delivery_outbox', ['available_at', 'created_at'], unique=False, postgresql_where=sa.text("status IN ('pending', 'failed') AND processed_at IS NULL"))
    op.create_table('refresh_tokens',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("token_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_refresh_tokens_token_hash_sha256_hex')),
    sa.CheckConstraint('used_at IS NULL OR used_at >= created_at', name=op.f('ck_refresh_tokens_use_not_before_creation')),
    sa.ForeignKeyConstraint(['session_id'], ['refresh_sessions.id'], name='fk_refresh_tokens_session_id_refresh_sessions', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('uq_refresh_tokens_session_active', 'refresh_tokens', ['session_id'], unique=True, postgresql_where=sa.text('used_at IS NULL'))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_check_constraint(op.f('ck_users_email_verification_not_before_creation'), 'users', 'email_verified_at IS NULL OR email_verified_at >= created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_users_email_verification_not_before_creation'), 'users', type_='check')
    op.drop_column('users', 'email_verified_at')
    op.drop_index('uq_refresh_tokens_session_active', table_name='refresh_tokens', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('refresh_tokens')
    op.drop_index('ix_authentication_delivery_outbox_pending', table_name='authentication_delivery_outbox', postgresql_where=sa.text("status IN ('pending', 'failed') AND processed_at IS NULL"))
    op.drop_table('authentication_delivery_outbox')
    op.drop_table('user_credentials')
    op.drop_index('ix_refresh_sessions_user_active', table_name='refresh_sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index('ix_refresh_sessions_family', table_name='refresh_sessions')
    op.drop_index('ix_refresh_sessions_expiry', table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index('uq_authentication_challenges_user_purpose_active', table_name='authentication_challenges', postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.drop_index('ix_authentication_challenges_expiry', table_name='authentication_challenges')
    op.drop_table('authentication_challenges')
    # ### end Alembic commands ###
