"""Public Phase 10 goal-planning application contracts."""

from falcon_api.goal_planning.analysis import (
    GoalPlanningAnalysis,
    analyze_goal_planning_snapshot,
)
from falcon_api.goal_planning.application import (
    GoalPlanGenerationCommand,
    MultiGoalOptimizationService,
)
from falcon_api.goal_planning.capacity import (
    CAPACITY_POLICY_VERSION,
    SavingsCapacityPlan,
    SavingsCapacityPoint,
    bridge_savings_forecast,
)
from falcon_api.goal_planning.contributions import (
    ContributionCreateCommand,
    ContributionRepository,
    ContributionService,
)
from falcon_api.goal_planning.feasibility import (
    FEASIBILITY_POLICY_VERSION,
    FeasibilityEvidenceReliability,
    GoalCompletionWindow,
    GoalDeadlineRiskLevel,
    GoalFeasibilityAssessment,
    GoalFeasibilityReasonCode,
    GoalFeasibilityState,
    assess_goal_feasibility,
    assess_snapshot_feasibility,
)
from falcon_api.goal_planning.greedy import (
    GREEDY_ALLOCATION_POLICY_VERSION,
    GoalAllocationProjection,
    GoalBaselineProjection,
    GoalMonthlyAllocation,
    GreedyAllocationBaseline,
    GreedyBaselineWarning,
    MonthlyAllocationPeriod,
    build_greedy_allocation_baseline,
    validate_allocation_inputs,
)
from falcon_api.goal_planning.guardrails import (
    DEFAULT_EMERGENCY_FUND_TARGET_MONTHS,
    OPTIMIZATION_GUARDRAIL_POLICY_VERSION,
    OptimizationGuardrailAssessment,
    OptimizationGuardrailReasonCode,
    OptimizationGuardrailStatus,
    evaluate_optimization_guardrails,
)
from falcon_api.goal_planning.optimizer import (
    CONSTRAINED_OPTIMIZATION_POLICY_VERSION,
    AllocationInvariantReport,
    AllocationInvariantViolation,
    ConstrainedOptimizationResult,
    ConstrainedOptimizationStatus,
    LinearProgramSolution,
    LinearProgramSolver,
    LinearSolverStatus,
    OptimizationReasonCode,
    SciPyHighsSolver,
    build_allocation_projections,
    calculate_weighted_funding_score,
    optimize_goal_allocations,
    verify_allocation_invariants,
)
from falcon_api.goal_planning.monitoring import (
    GOAL_PLAN_OPERATION_POLICY_VERSION,
    GoalPlanMonitor,
    GoalPlanOperation,
)
from falcon_api.goal_planning.persistence import (
    MAX_GOAL_PLAN_HISTORY,
    GoalPlanRepository,
)
from falcon_api.goal_planning.plan import (
    GOAL_OPTIMIZATION_PLAN_POLICY_VERSION,
    GoalContributionSchedule,
    GoalOptimizationPlan,
    GoalPlanAssumption,
    GoalPlanComparison,
    GoalPlanReasonCode,
    GoalPlanStrategy,
    build_goal_optimization_plan,
)
from falcon_api.goal_planning.progress import (
    GoalFundingState,
    GoalProgress,
    calculate_goal_progress,
    months_until_deadline,
)
from falcon_api.goal_planning.ranking import (
    RANKING_POLICY_VERSION,
    GoalRanking,
    GoalRankingReasonCode,
    GoalRankingScore,
    RankedGoal,
    rank_goal_assessments,
)
from falcon_api.goal_planning.repository import GoalRepository, GoalValues
from falcon_api.goal_planning.semantics import (
    GOAL_PLANNING_CONTRACT_VERSION,
    MAX_GOAL_LIST_LIMIT,
    GoalPlanningErrorCode,
    goal_status_can_transition,
    normalize_goal_currency,
    trusted_local_date,
)
from falcon_api.goal_planning.service import (
    GoalCreateCommand,
    GoalService,
    GoalUpdateCommand,
)
from falcon_api.goal_planning.snapshot import (
    GoalPlanningSnapshot,
    GoalPlanningSnapshotService,
    PlanningEvidenceRepository,
    PlanningSnapshotWarning,
)

__all__ = [
    "CAPACITY_POLICY_VERSION",
    "CONSTRAINED_OPTIMIZATION_POLICY_VERSION",
    "DEFAULT_EMERGENCY_FUND_TARGET_MONTHS",
    "FEASIBILITY_POLICY_VERSION",
    "GOAL_PLANNING_CONTRACT_VERSION",
    "GOAL_OPTIMIZATION_PLAN_POLICY_VERSION",
    "GOAL_PLAN_OPERATION_POLICY_VERSION",
    "GREEDY_ALLOCATION_POLICY_VERSION",
    "MAX_GOAL_LIST_LIMIT",
    "MAX_GOAL_PLAN_HISTORY",
    "OPTIMIZATION_GUARDRAIL_POLICY_VERSION",
    "RANKING_POLICY_VERSION",
    "AllocationInvariantReport",
    "AllocationInvariantViolation",
    "ConstrainedOptimizationResult",
    "ConstrainedOptimizationStatus",
    "ContributionCreateCommand",
    "ContributionRepository",
    "ContributionService",
    "FeasibilityEvidenceReliability",
    "GoalAllocationProjection",
    "GoalBaselineProjection",
    "GoalContributionSchedule",
    "GoalCompletionWindow",
    "GoalCreateCommand",
    "GoalDeadlineRiskLevel",
    "GoalFeasibilityAssessment",
    "GoalFeasibilityReasonCode",
    "GoalFeasibilityState",
    "GoalFundingState",
    "GoalMonthlyAllocation",
    "GoalOptimizationPlan",
    "GoalPlanGenerationCommand",
    "GoalPlanMonitor",
    "GoalPlanOperation",
    "GoalPlanRepository",
    "GoalPlanAssumption",
    "GoalPlanComparison",
    "GoalPlanReasonCode",
    "GoalPlanStrategy",
    "GoalPlanningAnalysis",
    "GoalPlanningErrorCode",
    "GoalPlanningSnapshot",
    "GoalPlanningSnapshotService",
    "GoalProgress",
    "GoalRanking",
    "GoalRankingReasonCode",
    "GoalRankingScore",
    "GoalRepository",
    "GoalService",
    "GoalUpdateCommand",
    "GoalValues",
    "GreedyAllocationBaseline",
    "GreedyBaselineWarning",
    "MonthlyAllocationPeriod",
    "MultiGoalOptimizationService",
    "LinearProgramSolution",
    "LinearProgramSolver",
    "LinearSolverStatus",
    "OptimizationGuardrailAssessment",
    "OptimizationGuardrailReasonCode",
    "OptimizationGuardrailStatus",
    "OptimizationReasonCode",
    "PlanningEvidenceRepository",
    "PlanningSnapshotWarning",
    "RankedGoal",
    "SavingsCapacityPlan",
    "SavingsCapacityPoint",
    "SciPyHighsSolver",
    "analyze_goal_planning_snapshot",
    "assess_goal_feasibility",
    "assess_snapshot_feasibility",
    "bridge_savings_forecast",
    "build_allocation_projections",
    "build_goal_optimization_plan",
    "build_greedy_allocation_baseline",
    "calculate_goal_progress",
    "calculate_weighted_funding_score",
    "evaluate_optimization_guardrails",
    "goal_status_can_transition",
    "months_until_deadline",
    "normalize_goal_currency",
    "optimize_goal_allocations",
    "rank_goal_assessments",
    "trusted_local_date",
    "validate_allocation_inputs",
    "verify_allocation_invariants",
]
